### PR TITLE
WIP: EP10 and EP11 - CDK support

### PR DESCRIPTION
**Pull request by leepa**
*Description of changes:*

CDK additions for Backend

- [x] CDK Template deployment
- [x] Install modules needed for booking system
- [x] Create step function for booking system
- [ ] Build pipeline changes to move to CDK for booking system deployment

## Resources

Here's some links of things to go read if you are interested in the CDK and the features we're using in this Pull Request:

[CDK Getting Started](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html)
[CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-construct-library.html)
[Step Functions Library](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by heitorlessa** [comment]
Due to changes in today's episode and next week (#27), we'll not be able to merge changes in the Makefile (`cdk deploy`), everything else is fine as they can be updated later

**Comment by pcariel** [comment]
Ping

**Comment by leepa** [comment]
This'll be after re:Invent - sorry!

**Comment by heitorlessa** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
