### PR TITLE
[WIP] EP1 - Project bootstrapping and AuthN/AuthZ with Cognito

### PR DESCRIPTION
**Pull request by heitorlessa**
*Issue #, if available:*

*Description of changes:*

**Episode**: https://www.twitch.tv/events/7uLkDzJbRvq9wvzg5j2rzQ

### Project Intro

* Demo
* GitHub - PR per Episode & Bonus Episode votes
* Tech stack - Diagram
* Tools walkthrough
    - Amplify CLI
    - Quasar
    - Vue Debug

### Bootstrapping & adding authentication

* ```amplify init```
* ```amplify auth add```
* ```amplify push```
* Amplify/VueJS integration
* Auth HOC
* Customize signup: https://aws-amplify.github.io/docs/js/vue#authenticator
* Federation and new OAuth features: 
    - **Sample repo**: https://github.com/awsed/amplify-oauth2
    - **Sample demo**: https://d30mfx0bo4fto0.cloudfront.net/

### Testing authentication

* Sign Up, etc.
* [Get user attributes](https://aws-amplify.github.io/docs/js/authentication#working-with-user-attributes)
* JWT Tooling
* Cognito Console, changes and attributes

### Resources

* [Amplify Get Started](https://aws-amplify.github.io/docs/)
* [Build on Serverless Season 2 - Schedule](https://pages.awscloud.com/GLOBAL-devstrategy-OE-BuildOnServerless-2019-reg-event.html)
* [Voting for Bonus Episode](https://github.com/aws-samples/aws-serverless-airline-booking/issues/1)
* [VueJS Amplify integration](https://aws-amplify.github.io/docs/js/vue)
* [Amplify Vue Authenticator component](https://aws-amplify.github.io/docs/js/vue)
* [Chrome Extension - Temp Mail](https://temp-mail.org/en/)
* [Temporary Emails](https://www.temp-mails.com/Number)
* [Chrome Extension - Octotree for GitHub](https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US)
* [JWT Online Decoder](https://jwt.io/)
* [Oh my zsh](https://ohmyz.sh/)
    - [Zshell Spaceship Theme](https://github.com/denysdovhan/spaceship-prompt)
    - [Auto-suggestions](https://github.com/zsh-users/zsh-autosuggestions)
* IDE: Visual Studio Code
    - Theme: Dracula Official Theme
    - Icons: Material Icons
    - [VSCode - Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)
    - [VSCode setup - Amplify Extension](https://marketplace.visualstudio.com/items?itemName=aws-amplify.aws-amplify-vscode)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dancomanlive** [comment]
Where is the link to the recording of the 1st episode on the 24th of April ?

**Comment by heitorlessa** [comment]
> Where is the link to the recording of the 1st episode on the 24th of April ?

Hey Dan - We'll be uploading to a YouTube playlist shortly this week, and I'll be updating here as well as letting everyone knows this Wed on Ep 2.

Thanks for the nudge

**Comment by heitorlessa** [comment]
PR created for Amplify Docs to avoid future confusion: https://github.com/aws-amplify/docs/pull/647

**Comment by heitorlessa** [comment]
> Where is the link to the recording of the 1st episode on the 24th of April ?

Here's the YouTube link: https://youtu.be/qBN98Co_0aw

Hope to see you tomorrow on Ep2 ;)

**Comment by kazinayem2011** [comment]
Which branch or tag should i start from for practicing from EP1? I mean the initial state of project where you started EP1.

**Comment by heitorlessa** [comment]
Hi Kazi - You night have some issues as Amplify CLI, and lots of frontend
components changed incl CVEs since then

I have a suggestion you could take to practice:

A) Start from the twitch branch (all episodes changes), and implement
enhancements that I can share with you to practice

B) If you can wait until July, I can strip out the frontend from all
functionalities (workshop branch), and write a draft README about how to
start from scratch

Let me know what works best for you

**Comment by sofian-ysf** [comment]
Hi, 
I was just wondering are the video recordings still available for this series. Would really be helpful.

Thanks,
Sofian

**Pull request merged**
