### PR TITLE
Serverless ETL: Flight data generation

### PR DESCRIPTION
**Pull request by mriccia**
Issue #47 [Catalog] ETL/Hydration process 

This PR includes a pipeline built with Step Functions to hydrate the flight catalog.

- The pipeline is triggered every 30 days (using CloudWatch Scheduled events)
- Flights are generated from a static set of Airports, using fake data
- Flights are generated for the following 30 days
- Flights are automatically deleted after they have "landed" (using DynamoDB TTL)
- Number of generated flights can be controlled via a parameter

Can you please take a look and suggest areas to change/fix before merging?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by heitorlessa** [comment]
hey @mriccia - This is awesome! Thank you so much for taking the time to work on this.

Could you add a README.md under `etl` explaining the solution in more detail?

Here's a model you can follow to remain consistent with other services - https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/src/backend/booking/README.md

Give me a shout if you need any help

**Comment by SimonEismann** [comment]
I ran into a minor issue with the auto-generated flight data. In `src/backend/etl/src/flights.js`, the ticket currency is set as `ticketCurrency: faker.finance.currencyCode()`, which results in each flight having a different, random currency.

This is an issue for two reason:
- The UI does not reflect this and always shows EUR (very minor)
- The auto generated prices are in the range of 0-1000, which makes for incredibly cheap flights in some currencies. However, Stripe has a minimum of 50 ct which then causes the booking to fail:

Log from the CreateStripeCharge lambda:
```
2020-04-28T15:20:56.419Z	bda9fd2a-ab7a-44c1-99dc-870280426fdd	INFO	{ Error: Amount must convert to at least 50 cents. Ar906 converts to approximately €0.22.
    at Function.generate (/var/task/node_modules/stripe/lib/Error.js:49:16)
    at IncomingMessage.res.once (/var/task/node_modules/stripe/lib/StripeResource.js:164:39)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at /var/task/node_modules/async-listener/glue.js:188:31
    at process._tickCallback (internal/process/next_tick.js:63:19)
  raw:
   { code: 'amount_too_small',
     doc_url: 'https://stripe.com/docs/error-codes/amount-too-small',
     message:
      'Amount must convert to at least 50 cents. Ar906 converts to approximately €0.22.',
     param: 'amount',
     type: 'invalid_request_error',
     headers:
      { server: 'nginx',
        date: 'Tue, 28 Apr 2020 15:20:56 GMT',
        'content-type': 'application/json',
        'content-length': '284',
        connection: 'keep-alive',
        'access-control-allow-credentials': 'true',
        'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
        'access-control-allow-origin': '*',
        'access-control-expose-headers':
         'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'access-control-max-age': '300',
        'cache-control': 'no-cache, no-store',
        'request-id': 'req_rTsqjc4bjFDSA6',
        'stripe-version': '2019-12-03',
        'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
     statusCode: 400,
     requestId: 'req_rTsqjc4bjFDSA6' },
  rawType: 'invalid_request_error',
  code: 'amount_too_small',
  param: 'amount',
  detail: undefined,
  headers:
   { server: 'nginx',
     date: 'Tue, 28 Apr 2020 15:20:56 GMT',
     'content-type': 'application/json',
     'content-length': '284',
     connection: 'keep-alive',
     'access-control-allow-credentials': 'true',
     'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
     'access-control-allow-origin': '*',
     'access-control-expose-headers':
      'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
     'access-control-max-age': '300',
     'cache-control': 'no-cache, no-store',
     'request-id': 'req_rTsqjc4bjFDSA6',
     'stripe-version': '2019-12-03',
     'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
  requestId: 'req_rTsqjc4bjFDSA6',
  statusCode: 400 }
```

**Comment by heitorlessa** [comment]
> I ran into a minor issue with the auto-generated flight data. In `src/backend/etl/src/flights.js`, the ticket currency is set as `ticketCurrency: faker.finance.currencyCode()`, which results in each flight having a different, random currency.
> 
> This is an issue for two reason:
> 
>     * The UI does not reflect this and always shows EUR (very minor)
> 
>     * The auto generated prices are in the range of 0-1000, which makes for incredibly cheap flights in some currencies. However, Stripe has a minimum of 50 ct which then causes the booking to fail:
> 
> 
> Log from the CreateStripeCharge lambda:
> 
> ```
> 2020-04-28T15:20:56.419Z	bda9fd2a-ab7a-44c1-99dc-870280426fdd	INFO	{ Error: Amount must convert to at least 50 cents. Ar906 converts to approximately €0.22.
>     at Function.generate (/var/task/node_modules/stripe/lib/Error.js:49:16)
>     at IncomingMessage.res.once (/var/task/node_modules/stripe/lib/StripeResource.js:164:39)
>     at Object.onceWrapper (events.js:286:20)
>     at IncomingMessage.emit (events.js:203:15)
>     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
>     at endReadableNT (_stream_readable.js:1145:12)
>     at /var/task/node_modules/async-listener/glue.js:188:31
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>   raw:
>    { code: 'amount_too_small',
>      doc_url: 'https://stripe.com/docs/error-codes/amount-too-small',
>      message:
>       'Amount must convert to at least 50 cents. Ar906 converts to approximately €0.22.',
>      param: 'amount',
>      type: 'invalid_request_error',
>      headers:
>       { server: 'nginx',
>         date: 'Tue, 28 Apr 2020 15:20:56 GMT',
>         'content-type': 'application/json',
>         'content-length': '284',
>         connection: 'keep-alive',
>         'access-control-allow-credentials': 'true',
>         'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
>         'access-control-allow-origin': '*',
>         'access-control-expose-headers':
>          'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
>         'access-control-max-age': '300',
>         'cache-control': 'no-cache, no-store',
>         'request-id': 'req_rTsqjc4bjFDSA6',
>         'stripe-version': '2019-12-03',
>         'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
>      statusCode: 400,
>      requestId: 'req_rTsqjc4bjFDSA6' },
>   rawType: 'invalid_request_error',
>   code: 'amount_too_small',
>   param: 'amount',
>   detail: undefined,
>   headers:
>    { server: 'nginx',
>      date: 'Tue, 28 Apr 2020 15:20:56 GMT',
>      'content-type': 'application/json',
>      'content-length': '284',
>      connection: 'keep-alive',
>      'access-control-allow-credentials': 'true',
>      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
>      'access-control-allow-origin': '*',
>      'access-control-expose-headers':
>       'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
>      'access-control-max-age': '300',
>      'cache-control': 'no-cache, no-store',
>      'request-id': 'req_rTsqjc4bjFDSA6',
>      'stripe-version': '2019-12-03',
>      'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
>   requestId: 'req_rTsqjc4bjFDSA6',
>   statusCode: 400 }
> ```

This is a great catch - Stripe payment amount, and currency. @mriccia stick with EUR as currency, and take a look at Simon's comment on the flight amount to prevent issues with the payment provider (I didn't know that).

**Comment by mriccia** [comment]
Thank you @SimonEismann for spotting and reporting the issue
@heitorlessa thanks for the guidance,  I'll fix this today

**Comment by heitorlessa** [comment]
Closing as we haven't managed to make progress

**Pull request closed without merging**
